name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the entire repository
      - name: Checkout repo
        uses: actions/checkout@v2

      # Change working directory to app
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Install dependencies in the app folder
      - name: Install dependencies
        working-directory: app
        run: yarn install

      # Build the React app
      - name: Build React App
        working-directory: app
        env:
          REACT_APP_SANITY_PROJECT_ID: ${{ secrets.VITE_SANITY_PROJECT_ID }}
          REACT_APP_SANITY_DATASET: ${{ secrets.VITE_SANITY_DATASET }}
        run: yarn build

      # Deploy the build folder from the app directory to the GitHub Pages repo
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: app/dist
          destination_repo: prajwalshah19.github.io
          publish_branch: build
